import { Injectable, Logger } from '@nestjs/common';
import * as XLSX from 'xlsx';
import type { AggregationResult } from './report-aggregation.service';

export interface ExcelRenderInput {
  reportNumber: string;
  donorName: string;
  templateName: string;
  grantReference: string;
  projectTitle: string;
  periodStart: Date;
  periodEnd: Date;
  currency: string;
  fxRateUsed: number;
  generatedAt: Date;
  generatedBy: string;
  aggregation: AggregationResult;
  /** Détail journal_line par compte (3ème onglet). */
  accountDetail: Array<{
    accountCode: string;
    accountLabel: string;
    totalDebit: number;
    totalCredit: number;
    netAmount: number;
  }>;
}

export const EXCEL_SHEET_SUMMARY = 'Summary';
export const EXCEL_SHEET_CATEGORIES = 'Detail by category';
export const EXCEL_SHEET_ACCOUNTS = 'Detail by account';

/**
 * Renderer Excel — 3 onglets :
 *
 * 1. **Summary** : métadonnées (donor, grant, période, devise) + totaux
 *    (budget, spent, overhead, funds carried).
 * 2. **Detail by category** : 1 ligne par categorie avec budget / spent /
 *    variance / variancePct + colonne alert.
 * 3. **Detail by account** : agrégation brute par compte SYSCEBNL (mappé
 *    ou non) — utile aux auditeurs bailleurs qui veulent remonter au plan
 *    comptable.
 */
@Injectable()
export class ExcelRenderService {
  private readonly logger = new Logger(ExcelRenderService.name);

  render(input: ExcelRenderInput): Buffer {
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, this.buildSummary(input), EXCEL_SHEET_SUMMARY);
    XLSX.utils.book_append_sheet(wb, this.buildCategories(input), EXCEL_SHEET_CATEGORIES);
    XLSX.utils.book_append_sheet(wb, this.buildAccounts(input), EXCEL_SHEET_ACCOUNTS);
    const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) as Buffer;
    this.logger.log(
      { reportNumber: input.reportNumber, size: buf.length, sheets: 3 },
      'donor report Excel rendered',
    );
    return buf;
  }

  private buildSummary(input: ExcelRenderInput): XLSX.WorkSheet {
    const a = input.aggregation;
    const rows: (string | number)[][] = [
      ['GRANTFLOW IPD — Donor financial report', ''],
      ['', ''],
      ['Report number', input.reportNumber],
      ['Donor', input.donorName],
      ['Template', input.templateName],
      ['Grant reference', input.grantReference],
      ['Project', input.projectTitle],
      ['Period start', input.periodStart.toISOString().slice(0, 10)],
      ['Period end', input.periodEnd.toISOString().slice(0, 10)],
      ['Currency', input.currency],
      ['FX rate (XOF→report)', input.fxRateUsed],
      ['Generated at', input.generatedAt.toISOString()],
      ['Generated by', input.generatedBy],
      ['', ''],
      ['Total budget', a.totalBudget],
      ['Total spent (direct + overhead)', a.totalSpent],
      ['Overhead amount', a.totalOverhead],
      ['Funds carried over', a.fundsCarried],
    ];
    const ws = XLSX.utils.aoa_to_sheet(rows);
    ws['!cols'] = [{ wch: 36 }, { wch: 36 }];
    return ws;
  }

  private buildCategories(input: ExcelRenderInput): XLSX.WorkSheet {
    const header = ['Code', 'Label', 'Budget', 'Spent', 'Variance', 'Variance %', 'Alert'];
    const data: (string | number | boolean)[][] = input.aggregation.lines.map((l) => [
      l.categoryCode,
      l.categoryLabel,
      l.budgetAmount,
      l.spentAmount,
      l.variance,
      l.variancePct,
      l.alert,
    ]);
    const ws = XLSX.utils.aoa_to_sheet([header, ...data]);
    ws['!cols'] = [
      { wch: 14 },
      { wch: 32 },
      { wch: 14 },
      { wch: 14 },
      { wch: 14 },
      { wch: 12 },
      { wch: 8 },
    ];
    return ws;
  }

  private buildAccounts(input: ExcelRenderInput): XLSX.WorkSheet {
    const header = ['Account code', 'Label', 'Total debit (XOF)', 'Total credit (XOF)', 'Net (XOF)'];
    const data: (string | number)[][] = input.accountDetail.map((a) => [
      a.accountCode,
      a.accountLabel,
      a.totalDebit,
      a.totalCredit,
      a.netAmount,
    ]);
    const ws = XLSX.utils.aoa_to_sheet([header, ...data]);
    ws['!cols'] = [{ wch: 12 }, { wch: 50 }, { wch: 18 }, { wch: 18 }, { wch: 18 }];
    return ws;
  }
}
